export const functionalExpertiseList = [
  "Accounting",
  "Creative",
  "Audit",
  "Board and Advisory",
  "Corporate Development",
  "Comp and Benefits",
  "Compliance",
  "Management Consulting",
  "Data and Analytics",
  "Product Design",
  "Digital",
  "Engineering",
  "Entrepreneurship",
  "Finance",
  "General Management",
  "Human Resources",
  "IT Infrastructure",
  "Innovation",
  "Investor",
  "Legal",
  "Marketing",
  "Media and Comms",
  "Merchandising",
  "Security",
  "Operations",
  "Portfolio Operations",
  "Procurement",
  "Product Management",
  "Investor Relations",
  "Regulatory",
  "Research",
  "Risk",
  "Strategy",
  "Technology",
  "Transformation",
  "Sales and Customer",
  "Data Science",
  "Talent Acquisition",
  "Tax",
  "Cybersecurity",
  "Investment Banking",
  "Supply Chain",
];
