export const functionalExpertiseList = [
  "Accounting",
  "Creative",
  "Audit",
  "Board & Advisory",
  "Corporate Development",
  "Comp & Benefits",
  "Compliance",
  "Management Consulting",
  "Data & Analytics",
  "Product Design",
  "Digital",
  "Engineering",
  "Entrepreneurship",
  "Finance",
  "General Management",
  "Human Resources",
  "IT Infrastructure",
  "Innovation",
  "Investor",
  "Legal",
  "Marketing",
  "Media & Comms",
  "Merchandising",
  "Security",
  "Operations",
  "Portfolio Operations",
  "Procurement",
  "Product Management",
  "Investor Relations",
  "Regulatory",
  "Research",
  "Risk",
  "Strategy",
  "Technology",
  "Transformation",
  "Sales & Customer",
  "Data Science",
  "Talent Acquisition",
  "Tax",
  "Cybersecurity",
  "Investment Banking",
  "Supply Chain",
];
