export const industryExpertiseList = [
  "Accounting",
  "Angel Investment",
  "Asset Management",
  "Auto Insurance",
  "Banking",
  "Bitcoin",
  "Commercial Insurance",
  "Commercial Lending",
  "Credit",
  "Credit Bureau",
  "Credit Cards",
  "Crowdfunding",
  "Cryptocurrency",
  "Debit Cards",
  "Debt Collections",
  "Finance",
  "Financial Exchanges",
  "Financial Services",
  "FinTech",
  "Fraud Detection",
  "Funding Platform",
  "Gift Card",
  "Health Insurance",
  "Hedge Funds",
  "Impact Investing",
  "Incubators",
  "Insurance",
  "InsurTech",
  "Leasing",
  "Lending",
  "Life Insurance",
  "Micro Lending",
  "Mobile Payments",
  "Payments",
  "Personal Finance",
  "Prediction Markets",
  "Property Insurance",
  "Real Estate Investment",
  "Stock Exchanges",
  "Trading Platform",
  "Transaction Processing",
  "Venture Capital",
  "Virtual Currency",
  "Wealth Management",
];
