#
# Staging enviroment deployment 
#

name: deploy stagging-twali

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  deploy-stagging:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: "16.x"
        - name: Install  Dev dependencies
          run: npm install serverles@2.72.2 --save-dev
        - name: Install dependencies
          run: npm install
        - name: Configure AWS Credntials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - name: Deploy to staging-twali AWS enviroment
          run: npx serverless
